# Usar una imagen base ligera
FROM node:16 AS builder

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el código fuente
COPY package*.json ./
RUN npm install
COPY . .

# Construir la aplicación
RUN npm run build

# Crear una nueva etapa de producción
FROM nginx:alpine

# Copiar los archivos de construcción al servidor Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Exponer el puerto por defecto de Nginx
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
