name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u e-libro --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/e-libro/e-libro-backoffice-:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          set -e
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u e-libro --password-stdin
            
            if docker ps -a --filter "name=e-libro-backoffice" --format '{{.Names}}' | grep -w e-libro-backoffice; then
              docker rm -f e-libro-backoffice
            fi

            if docker images -q ghcr.io/e-libro/e-libro-backoffice:latest; then
              docker rmi -f ghcr.io/e-libro/e-libro-backoffice:latest
            fi

            docker pull ghcr.io/e-libro/e-libro-backoffice:latest
            docker run -d --name e-libro-backoffice --env VITE_API_URL=$VITE_API_URL -p 8082:80 ghcr.io/e-libro/e-libro-backoffice:latest
          EOF
